version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password